### ISSUE TITLE
文章编辑页面缺少引用文件

### ISSUE THREAD

**Issue by sniperZj** [eumji025/EumJi-blog#13]
articleEdit.html
   @@@出错段
 <script src="/admin/js/jquery-2.1.1.min.js"></script>
        <script src="/admin/js/bootstrap.min.js"></script>
        <script src="/admin/js/editormd.js"></script>
        <script src="/admin/js/jquery.form.js"></script>
        <script src="/admin/js/plugins/chosen/chosen.jquery.js"></script>
        <script src="/admin/js/article/edit_article.js"></script>
        <script src="/admin/js/validation.js"></script>
        <script type="text/javascript" src="/admin/js/flavr/flavr/js/flavr.min.js"></script>
        <script type="text/javascript" src="/admin/js/flavr/base.js"></script>

**Comment by eumji025** [comment]
忘记修改了，特殊页面。。。。。。
