### ISSUE TITLE
偷偷嵌入隐藏很深的金融诈骗广告,您真有意思

### ISSUE THREAD

**Issue by alpzxy** [eumji025/EumJi-blog#21]
做人不要这么贱啊

**Comment by eumji025** [comment]
什么意思,我做什么广告了???

**Comment by shenzhuan** [comment]
开源的  有广告 你不用就是了 ，  后台添加文章 怎么中午乱码了？ 不是utf-8？

**Comment by eumji025** [comment]
@shenzhuan 配置一下连接信息或者在创建库的时候设置为UTF-8

**Comment by zhchyun** [comment]
提个无聊的bug，注释中诗句应该为 【不积跬步，无以至千里；不积小流，无以成江海】

**Comment by eumji025** [comment]
@zhchyun 难怪我在其他地方也发现了类似的情况。。。。。
