### ISSUE TITLE
建议!!!

### ISSUE THREAD

**Issue by MOONYANYI** [eumji025/EumJi-blog#24]
评论为啥要登录,就算要登录,也不至于一定要绑定手机号吧

**Comment by eumji025** [comment]
@MOONYANYI  如果有广告的话可以找到地方提交一下哦,时间太久我也忘记了.

另外评论是使用第三方的评论系统 `畅言` 所以不是我能控制的,主要还是现在留言要求越来越严了吧 

望理解
